name: {{name.snakeCase()}}
description: "A new Flutter project." # TODO: edit this

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  collection: ^1.18.0
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mcquenji_core:
    git:
      url: https://github.com/mcquenji/mcquenji_core.git
  {{#firebase}}
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  mcquenji_firebase:
    git:
      url: https://github.com/mcquenji/mcquenji_firebase.git
  {{/firebase}}
  path: ^1.9.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  architecture_linter: ^0.2.2
  build_runner: ^2.4.11
  flutter_gen: ^5.6.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutterando_analysis: ^0.0.2
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false
